Awx dev
cedadev/jasmin-appliances pull request #13
Opened 2019-02-27 10:52 UTC by hollysilk

Changes required for version working within an AWX context

2019-02-27 11:20 UTC, brtkwr approved these changes
lgtm

2019-02-27 11:20 UTC, brtknr commented on config/slurm.yml
> +    - uuid: "8723c186-d15f-44d5-9421-e12bf2a03325"
is there any reason we are specifying both uuid and ip other than ease? wouldn't it be nicer to retrieve the floating ip using the cli from the uuid instead?

2019-03-05 09:25 UTC, oneswig requested changes
Looks like there's a merge conflict with master to resolve - can the requirements.yml be updated when that gets dealt with.  Otherwise, looks good.

2019-03-05 09:25 UTC, oneswig commented on roles/requirements.yml
> +- src: https://github.com/stackhpc/jasmin-cluster-infra-ansible
The `issue-23` PR has been merged, before this commit gets merged can we update this?

2019-03-11 10:24 UTC, merged