Defined nfs_clients group at the playbook level
cedadev/jasmin-appliances pull request #7
Opened 2019-02-12 16:08 UTC by hollysilk

2019-02-22 17:22 UTC, priteau requested changes
Looks like this needs to be updated to merge.

2019-02-25 14:35 UTC, hollysilk commented
I've resolved the conflicts now. But I presume we also want to do something similar when using BeeGFS now? At the moment we are still defining BeeGFS clients in the config file.

2019-03-01 09:58 UTC, hollysilk commented
This corresponds to issue #22. It would mean we stop defining the `extra_groups` variable from within the slurm config file. We instead define the Slurm cluster as `nfs_clients` or `beefs_clients` from within the relevant playbook.

2019-03-06 16:42 UTC, brtkwr approved these changes

2019-03-11 10:25 UTC, merged